### ISSUE TITLE
index out of bounds: the len is 10 but the index is 18446744073709551615

### ISSUE THREAD

**Issue by 1sra3l** [fltk-rs/fl2rust#15]
https://github.com/fltk-rs/fl2rust/blob/62e26384b84fb7a782fd4a30093cfb9c611bdec0/src/gen.rs#L177

I think it shoule be
```rs
for i in 1..props.len() {
// since you use props[i - 1]
```

**Comment by MoAlyousef** [comment]
Hi
Do you have a reproducer which invokes this?

**Comment by MoAlyousef** [comment]
I've pushed a fix which uses optionals and wrapping sub.

**Comment by 1sra3l** [comment]
@MoAlyousef it is still happenening unless I modify to 0 to 1 again.
I have tried both using a manual version `fl2rust in.fl > out.rs` as well as manually editing my installed version and deleting my deps to rebuild the changes.

This is by far the most intricate FLUID file I have ever used with the program, it is 1247 lines, otherwise I'd post it here.
If the 0 should work (like it used to) it seems there is likely some item I am using you did not include, or something along those lines.

**Comment by 1sra3l** [comment]
Though, if you just want me to post it anyhow I can :smile:

**Comment by MoAlyousef** [comment]
Does it also happen with the latest changes?
If you could upload it or send it privately, it would provide a good test case.

**Comment by MoAlyousef** [comment]
I've tried the latest changes on the file you sent me and it seems to work correctly. Can you try again?

**Comment by MoAlyousef** [comment]
Were you able to verify the latest release?

**Comment by 1sra3l** [comment]
This does indeed fix it! Thanks so much I will close this!
